### ISSUE TITLE
Throwing syntax error for yarn manifest command

### ISSUE THREAD

**Issue by pranjalBakshi** [facebook/fbt#165]
I just cloned the repo and started executing the commands to run the demo-app and it gives syntax error for yarn manifest command. This is the error I am getting - SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:1054:16) . Please provide the fix for this.

**Comment by kayhadrin** [comment]
Hi @pranjalBakshi,

I'm sorry you're having issues using the demo app.
Could you share more details about your setup and what command line actions you did to get this error?

It'd be great if you could use the current bug report template to submit this info:

````
## 🐛 Bug Report

<!-- A clear and concise description of what the bug is. -->

## To Reproduce

Steps to reproduce the behavior:

## Expected behavior

<!-- A clear and concise description of what you expected to happen. -->

## Link to repo (highly encouraged) or paste

<!--
Please provide either a minimal repository on GitHub or a code snippet
demonstrating the problem.  Issues without a reproduction link are likely to
stall.
-->

## envinfo

<!-- Run `npx envinfo --system --binaries` Paste the results here: -->

```bash

```

````

It'd be especially useful to know the git commit hash or npm module versions of the fbt packages you're using.

**Comment by pranjalBakshi** [comment]
## 🐛 Bug Report



## To Reproduce

Steps to reproduce the behavior: 
1. Download zip(master branch) and unzip and went to this directory fbt-master\fbt-master\demo-app> 
2. Ran command yarn install and it gave error 

Error: Cannot find module '\fbt-master\fbt-master\node_modules\node_modules\@babel\node\bin\babel-node.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

3. Tried to run yarn manifest command which gave this error 


SyntaxError: missing ) after argument list
    at wrapSafe (internal/modules/cjs/loader.js:1054:16)
    at Module._compile (internal/modules/cjs/loader.js:1102:27)
    at Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Object.newLoader [as .js] (\fbt-master\fbt-master\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at Object.<anonymous> (\fbt-master\fbt-master\node_modules\@babel\node\lib\_babel-node.js:234:23)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)


## Expected behavior



## Link to repo (highly encouraged) or paste



## envinfo

**Comment by kayhadrin** [comment]
Alright, that's enough info to get started.

Could you run these commands to ensure the npm packages of the project root folder have been installed before using the demo-app?

```
cd fbt-master # that's the parent folder of `demo-app`
yarn install
cd demo-app
yarn clean-build
```

I think this should fix the issue.

**Comment by pranjalBakshi** [comment]
okay I tried this - 
cd fbt-master # that's the parent folder of `demo-app`
yarn install
cd demo-app
yarn clean-build

and I got this error now - 

yarn run v1.22.5
$ yarn clean-fbts && yarn install && yarn build
$ rm .enum_manifest.json .src_manifest.json .source_strings.json src/translatedFbts.json 2&> /dev/null || exit 0
|| was unexpected at this time.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by kayhadrin** [comment]
Could you share more info about your Operating System? And version?
What is your shell environment name and version?

Finally, could you retry that command with the `--verbose` option and share the output?

`yarn --verbose clean-build`

**Comment by pranjalBakshi** [comment]
Tried with --verbose option and got the same error. 

System:
    OS: Windows 10 10.0.19041
  Binaries:
    Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD

I am using VS code as IDE.

**Comment by kayhadrin** [comment]
Our scripts are written for a *nix environment, that's why it's not working on Windows.

I'd recommend you to try using the Windows Subsystem for Linux, Git Bash, or Cygwin instead.
Personally, I used Cygwin to test this on a Windows machine about 12 months ago without issues.

**Comment by kayhadrin** [comment]
Closing this issue for now.

**Comment by SoftwareDesign-Solution** [comment]
I had the same problem under windows with command line and git bash

mail@SURFACEV7 MINGW64 /d/Playground/React/react-fbt (master)
$ npm run manifest

> react-fbt@0.1.0 manifest
> babel-node node_modules/.bin/fbt-manifest --src src

D:\Playground\React\react-fbt\node_modules\.bin\fbt-manifest:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at wrapSafe (node:internal/modules/cjs/loader:1281:20)
    at Module._compile (node:internal/modules/cjs/loader:1321:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.newLoader [as .js] (D:\Playground\React\react-fbt\node_modules\pirates\lib\index.js:121:7)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Module._load (node:internal/modules/cjs/loader:1024:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:174:12)
    at Object.<anonymous> (D:\Playground\React\react-fbt\node_modules\@babel\node\lib\_babel-node.js:145:21)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)

Node.js v20.16.0
