### ISSUE TITLE
Script collectFBT.js failed with a human unreadable error 

### ISSUE THREAD

**Issue by retyui** [facebook/fbt#82]
When you forgot add a `many` prop:
```js
<fbt:plural {/*many="seals"*/} showCount="ifMany" count={Number(count)}>
              a seal
</fbt:plural>
```

You will see an error like this:
```sh
src/Plurals/index.js:
	TypeError: Cannot read property 'start' of undefined
/home/i/open-source/fbtDemo/node_modules/babel-plugin-fbt/bin/collectFBT.js:156
    throw new Error(`Failed in ${errCount} files`);
    ^

Error: Failed in 1 files
    at writeOutput (/home/i/open-source/fbtDemo/node_modules/babel-plugin-fbt/bin/collectFBT.js:156:11)
    at ReadStream.<anonymous> (/home/i/open-source/fbtDemo/node_modules/babel-plugin-fbt/bin/collectFBT.js:194:5)
    at ReadStream.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by kayhadrin** [comment]
I'm currently working on a refactor that'll improve the error message for this.

It'll look like this:

> Error: The 'many' attribute must be set explicitly if showing count only on 'ifMany', since the singular form presumably starts with an article

**Comment by kayhadrin** [comment]
Fixed. Now, it'll show this new error message:

> Error: The 'many' attribute must be set explicitly if showing count only on 'ifMany', since the singular form presumably starts with an article
